### ISSUE TITLE
Data folder permissions

### ISSUE THREAD

**Issue by m-klecka** [Donkie/Spoolman#173]
Hi, i created unraid template for Spoolman, but i'm having trouble with permissions for the data folder (/home/app/.local/share/spoolman). In unraid, the bound fonder is created with "drwxr-xr-x" and shows this error

`Traceback (most recent call last):
  File "/home/app/spoolman/.venv/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/app/spoolman/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/spoolman/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/app/spoolman/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/spoolman/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/spoolman/.venv/lib/python3.11/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/app/spoolman/.venv/lib/python3.11/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/app/spoolman/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/app/spoolman/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/app/spoolman/.venv/lib/python3.11/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/spoolman/.venv/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/app/spoolman/spoolman/main.py", line 21, in <module>
    file_handler = TimedRotatingFileHandler(log_file, when="midnight", backupCount=5)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/handlers.py", line 214, in __init__
    BaseRotatingHandler.__init__(self, filename, 'a', encoding=encoding,
  File "/usr/local/lib/python3.11/logging/handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/usr/local/lib/python3.11/logging/__init__.py", line 1181, in __init__
    StreamHandler.__init__(self, self._open())
                                 ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 1213, in _open
    return open_func(self.baseFilename, self.mode,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/home/app/.local/share/spoolman/spoolman.log'`

 if i change it to "drwxr-xrwx" it shows no errors and starts like it should. 
Dont know if its unraid error or the container. Any tips how to fix this, other than manualy changing permissions in unraid? Maybe changing owner of the folder in the container? I looked at some other containers' dockerfile, and they usually create folders with chmod 777 or with chown 99:100.

Thanks

**Comment by Donkie** [comment]
See if the discussions here help you #143

**Comment by m-klecka** [comment]
> See if the discussions here help you #143

it does not help. If i map the folder /data inside container to outside folder, then nothing appears in there, because nothing is there. Its clearly a permission issue inside container for the folder you specify to map in the docker compose file.

**Comment by Donkie** [comment]
I have now put in place two measures for the next release to help reduce this issue in the future:

1. Spoolman will now crash with a helpful error if it doesn't have permissions to write to the data dir
2. A big warning will appear in the logs if you haven't mounted the data dir correctly

**Comment by Fribb** [comment]
@Donkie would it be possible that we get environmental variables for the IDs of the user and group so that we can pass them to the container?

While using Unraid, the ownership is nobody:users (99:100) and while chown'ing the data folder will now let the spoolman.log file be created, it also now has a different convention as the rest of the system. I would now have to connect to my Server running Spoolman in the docker container and manually delete it with the root user instead of just opening the network share and deleting it.

**Comment by Donkie** [comment]
yeah the UID GID thing is something I also want to implement, it's quite complicated though so been putting off doing it.

**Comment by Donkie** [comment]
Made a new issue for that: #204 
I'll close this issue for now
