### ISSUE TITLE
Unable to configure spoolman in Moonraker config - Creality Sonic Pad

### ISSUE THREAD

**Issue by ale-ben** [Donkie/Spoolman#198]
I set up Spoolman in a container and it works perfectly and responds to http://192.168.1.229:7912.

I'm trying to configure moonraker on my Sonic Pad to work with spoolman but after adding the following to moonraker.config I get an error.

- [X] spoolman and moonraker are in the same network
- [X] spoolman is accessible using the URL provided to moonraker 

Config: 
```
[spoolman]
server: http://192.168.1.229:7912
#   URL to the Spoolman instance. This parameter must be provided.
sync_rate: 5
#   The interval, in seconds, between sync requests with the
#   Spoolman server.  The default is 5.
```

Error:
```
#################################################################
All Configuration Files:
/mnt/UDISK/printer_config/moonraker.conf
#################################################################
[ERROR] 2023-11-15 10:56:50,281 [root] [database:__init__:120] ##########/mnt/UDISK/.moonraker_database
[ERROR] 2023-11-15 11:46:22,025 [root] [common:build_error:575] JSON-RPC Request Error: -32601
{"code":"key86", "msg": "Metadata not available for <>", "values": [""]}
Traceback (most recent call last):
  File "/usr/share/moonraker/moonraker/common.py", line 541, in execute_method
    result = await callback(params)
  File "/usr/share/moonraker/moonraker/websockets.py", line 115, in func
    ip_addr=sc.ip_addr, user=sc.user_info))
  File "/usr/share/moonraker/moonraker/components/file_manager/file_manager.py", line 417, in _handle_metadata_request
    """{"code":"key86", "msg": "Metadata not available for <""" + requested_file + """>", "values": [""" + '"' + requested_file + '"' + """]}""", 404)
moonraker.utils.ServerError: {"code":"key86", "msg": "Metadata not available for <>", "values": [""]}
[ERROR] 2023-11-15 11:48:56,933 [root] [database:__init__:120] ##########/mnt/UDISK/.moonraker_database
[ERROR] 2023-11-15 11:48:57,080 [root] [server:load_component:283] Unable to load component: (spoolman)
Traceback (most recent call last):
  File "/usr/share/moonraker/moonraker/server.py", line 275, in load_component
    module = importlib.import_module(full_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'moonraker.components.spoolman'
```

I suspect it is a problem with Sonic Pad but, just to be sure, I would like your opinion since I can find nothing in internet.

Log file: [moonraker.log](https://github.com/Donkie/Spoolman/files/13363781/moonraker.log)

**Comment by Donkie** [comment]
Judging by the error it looks like you have a too old moonraker installed.

**Comment by ale-ben** [comment]
Turns out sonic pad has a quite outdated version of klipper/moonraker.
Sorry for the bother....
