### ISSUE TITLE
UNRAID Docker startup error

### ISSUE THREAD

**Issue by IanAlbinson** [Donkie/Spoolman#218]
Any thoughts on this error? Just installed, starts but immediately stops.

+++

INFO:     Started server process [1]
INFO:     Waiting for application startup.
spoolman.main              INFO     Starting Spoolman v0.14.0 (commit: 286e519) (built: 2023-12-02 11:16:35+00:00)
spoolman.main              INFO     Using data directory: /home/app/.local/share/spoolman
spoolman.main              INFO     Using logs directory: /home/app/.local/share/spoolman
spoolman.main              INFO     Using backups directory: /home/app/.local/share/spoolman/backups
spoolman.main              INFO     Setting up database...
ERROR:    Traceback (most recent call last):
  File "/home/app/spoolman/spoolman/env.py", line 89, in get_port
    return int(port)
           ^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'remove variable if not used'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/app/spoolman/.venv/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/home/app/spoolman/.venv/lib/python3.11/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/home/app/spoolman/.venv/lib/python3.11/site-packages/starlette/routing.py", line 654, in startup
    await handler()
  File "/home/app/spoolman/spoolman/main.py", line 87, in startup
    database.setup_db(database.get_connection_url())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/spoolman/spoolman/database/database.py", line 25, in get_connection_url
    port = env.get_port()
           ^^^^^^^^^^^^^^
  File "/home/app/spoolman/spoolman/env.py", line 91, in get_port
    raise ValueError(f"Failed to parse SPOOLMAN_DB_PORT variable: {exc!s}") from exc
ValueError: Failed to parse SPOOLMAN_DB_PORT variable: invalid literal for int() with base 10: 'remove variable if not used'

ERROR:    Application startup failed. Exiting.

+++

**Comment by Donkie** [comment]
You can't leave any of the DB variables empty in the Unraid Spoolman config. If you don't use them, remove them.
