### ISSUE TITLE
Can't update to 0.15

### ISSUE THREAD

**Issue by mfraser** [Donkie/Spoolman#257]
Followed the instructions on updating to a newer version on Ubuntu Server 22.04, but I'm getting:

```
pdm.termui: Error occurs
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests_toolbelt/_compat.py", line 48, in <module>
    from requests.packages.urllib3.contrib import appengine as gaecontrib
ImportError: cannot import name 'appengine' from 'requests.packages.urllib3.contrib' (/home/mfraser/.local/lib/python3.10/site-packages/urllib3/contrib/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mfraser/.local/lib/python3.10/site-packages/pdm/termui.py", line 246, in logging
    yield logger
  File "/home/mfraser/.local/lib/python3.10/site-packages/pdm/cli/actions.py", line 215, in do_sync
    synchronizer.synchronize()
  File "/home/mfraser/.local/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 459, in synchronize
    self.candidates[self_key] = self.self_candidate
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/mfraser/.local/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 140, in self_candidate
    return self.environment.project.make_self_candidate(not self.no_editable)
  File "/home/mfraser/.local/lib/python3.10/site-packages/pdm/project/core.py", line 518, in make_self_candidate
    can.prepare(self.environment).metadata
  File "/home/mfraser/.local/lib/python3.10/site-packages/pdm/models/candidates.py", line 600, in metadata
    result = self.prepare_metadata()
  File "/home/mfraser/.local/lib/python3.10/site-packages/pdm/models/candidates.py", line 495, in prepare_metadata
    self._unpack(validate_hashes=False)
  File "/home/mfraser/.local/lib/python3.10/site-packages/pdm/models/candidates.py", line 460, in _unpack
    with self.environment.get_finder() as finder:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/mfraser/.local/lib/python3.10/site-packages/pdm/environments/base.py", line 144, in get_finder
    session = self._build_session(trusted_hosts)
  File "/home/mfraser/.local/lib/python3.10/site-packages/pdm/environments/base.py", line 80, in _build_session
    from pdm.models.session import PDMSession
  File "/home/mfraser/.local/lib/python3.10/site-packages/pdm/models/session.py", line 11, in <module>
    from requests_toolbelt.utils import user_agent
  File "/usr/lib/python3/dist-packages/requests_toolbelt/__init__.py", line 12, in <module>
    from .adapters import SSLAdapter, SourceAddressAdapter
  File "/usr/lib/python3/dist-packages/requests_toolbelt/adapters/__init__.py", line 12, in <module>
    from .ssl import SSLAdapter
  File "/usr/lib/python3/dist-packages/requests_toolbelt/adapters/ssl.py", line 16, in <module>
    from .._compat import poolmanager
  File "/usr/lib/python3/dist-packages/requests_toolbelt/_compat.py", line 50, in <module>
    from urllib3.contrib import appengine as gaecontrib
ImportError: cannot import name 'appengine' from 'urllib3.contrib' (/home/mfraser/.local/lib/python3.10/site-packages/urllib3/contrib/__init__.py)
```
Seems to be failing at this line:
`pdm config venv.backend venv`

**Comment by mfraser** [comment]
I had to user install requests-toolbelt.

`python3 -m pip install --upgrade requests-toolbelt`
