### ISSUE TITLE
Install pydantic 1.10.12 failed

### ISSUE THREAD

**Issue by Bersaker** [Donkie/Spoolman#284]
Hi.

If i would install Spoolman, i have this Problem...

`pi@test:~/Spoolman $ bash ./scripts/install_debian.sh
Python 3.9 or later is installed (Current version: 3.9.2)
Updating apt-get cache...
Hit:1 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Reading package lists... Done
Updating pip...
Pip updated successfully.
Installing system-wide pip packages needed for Spoolman...
Installing Spoolman backend and its dependencies using PDM...
WARNING: Lockfile is generated on an older version of PDM
Synchronizing working set with resolved packages: 1 to add, 0 to update, 0 to remove

  ✖ Install pydantic 1.10.12 failed
Retry failed jobs
  ✖ Install pydantic 1.10.12 failed

ERRORS:
add pydantic failed:
Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 286, in install_candidate
    self.manager.install(can)
  File "/home/pi/.local/lib/python3.9/site-packages/pdm/installers/manager.py", line 34, in install
    dist_info = installer(str(prepared.build()), self.environment, prepared.direct_url())
  File "/home/pi/.local/lib/python3.9/site-packages/pdm/models/candidates.py", line 403, in build
    self.obtain(allow_all=False)
  File "/home/pi/.local/lib/python3.9/site-packages/pdm/models/candidates.py", line 440, in obtain
    self.link = _find_best_match_link(
  File "/home/pi/.local/lib/python3.9/site-packages/pdm/models/candidates.py", line 106, in _find_best_match_link
    found = attempt_to_find()
  File "/home/pi/.local/lib/python3.9/site-packages/pdm/models/candidates.py", line 97, in attempt_to_find
    best = finder.find_best_match(req.as_line(), hashes=hashes).best
  File "/home/pi/.local/lib/python3.9/site-packages/unearth/finder.py", line 368, in find_best_match
    best_match = next(iter(applicable_candidates), None)
  File "/home/pi/.local/lib/python3.9/site-packages/unearth/finder.py", line 301, in _find_packages_from_requirement
    yield from self._find_packages(requirement.name, allow_yanked)
  File "/home/pi/.local/lib/python3.9/site-packages/unearth/finder.py", line 267, in _find_packages
    return sorted(all_packages, key=self._sort_key, reverse=True)
  File "/home/pi/.local/lib/python3.9/site-packages/unearth/collector.py", line 135, in collect_links_from_location
    yield from _collect_links_from_index(session, location)
  File "/home/pi/.local/lib/python3.9/site-packages/unearth/collector.py", line 85, in parse_json_response
    data = json.loads(page.content)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 119703 (char 119702)

See /tmp/pdm-install-ipbinizb.log for detailed debug log.
[InstallationError]: Some package operations are not complete yet
WARNING: Add '-v' to see the detailed traceback
pi@test:~/Spoolman $`

**Comment by Donkie** [comment]
Did you try again? Seems like the install was aborted perhaps due to some network issue

**Comment by n4t3y** [comment]
Hi, I'm having the same issue - any ideas how I can get it to work?
