### ISSUE TITLE
No Web UI

### ISSUE THREAD

**Issue by Hesi-Re** [Donkie/Spoolman#38]
Hi. I want to run Docker in the same Raspberry Pi as Klipper/Moonraker.

I installed Docker with this line commands:
curl -sSL https://get.docker.com | sh
sudo usermod -aG docker pi

My Docker installation is running well: 
When I run command "docker run hello-world" I get the right info.

Then I created a folder called spool man and inside it I created a file called docker-compose.yml and a folder called data.

Inside docker-compose.yml I pasted the text:

**Comment by Donkie** [comment]
You should first of all try to get the docker logs of the container. Do

docker-compose logs

And see if it contains anything that looks like an error

**Comment by Hesi-Re** [comment]
Here is the log:

spoolman-spoolman-1  | Traceback (most recent call last):
spoolman-spoolman-1  |   File "/home/app/.venv/bin/uvicorn", line 5, in <module>
spoolman-spoolman-1  |     from uvicorn.main import main
spoolman-spoolman-1  |   File "/home/app/.venv/lib/python3.11/site-packages/uvicorn/__init__.py", line 1, in <module>
spoolman-spoolman-1  |     from uvicorn.config import Config
spoolman-spoolman-1  |   File "/home/app/.venv/lib/python3.11/site-packages/uvicorn/config.py", line 1, in <module>
spoolman-spoolman-1  |     import asyncio
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/asyncio/__init__.py", line 8, in <module>
spoolman-spoolman-1  |     from .base_events import *
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 18, in <module>
spoolman-spoolman-1  |     import concurrent.futures
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/concurrent/futures/__init__.py", line 8, in <module>
spoolman-spoolman-1  |     from concurrent.futures._base import (FIRST_COMPLETED,
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 7, in <module>
spoolman-spoolman-1  |     import logging
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/logging/__init__.py", line 58, in <module>
spoolman-spoolman-1  |     _startTime = time.time()
spoolman-spoolman-1  |                  ^^^^^^^^^^^
spoolman-spoolman-1  | PermissionError: [Errno 1] Operation not permitted
spoolman-spoolman-1  | Traceback (most recent call last):
spoolman-spoolman-1  |   File "/home/app/.venv/bin/uvicorn", line 5, in <module>
spoolman-spoolman-1  |     from uvicorn.main import main
spoolman-spoolman-1  |   File "/home/app/.venv/lib/python3.11/site-packages/uvicorn/__init__.py", line 1, in <module>
spoolman-spoolman-1  |     from uvicorn.config import Config
spoolman-spoolman-1  |   File "/home/app/.venv/lib/python3.11/site-packages/uvicorn/config.py", line 1, in <module>
spoolman-spoolman-1  |     import asyncio
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/asyncio/__init__.py", line 8, in <module>
spoolman-spoolman-1  |     from .base_events import *
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 18, in <module>
spoolman-spoolman-1  |     import concurrent.futures
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/concurrent/futures/__init__.py", line 8, in <module>
spoolman-spoolman-1  |     from concurrent.futures._base import (FIRST_COMPLETED,
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 7, in <module>
spoolman-spoolman-1  |     import logging
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/logging/__init__.py", line 58, in <module>
spoolman-spoolman-1  |     _startTime = time.time()
spoolman-spoolman-1  |                  ^^^^^^^^^^^
spoolman-spoolman-1  | PermissionError: [Errno 1] Operation not permitted
spoolman-spoolman-1  | Traceback (most recent call last):
spoolman-spoolman-1  |   File "/home/app/.venv/bin/uvicorn", line 5, in <module>
spoolman-spoolman-1  |     from uvicorn.main import main
spoolman-spoolman-1  |   File "/home/app/.venv/lib/python3.11/site-packages/uvicorn/__init__.py", line 1, in <module>
spoolman-spoolman-1  |     from uvicorn.config import Config
spoolman-spoolman-1  |   File "/home/app/.venv/lib/python3.11/site-packages/uvicorn/config.py", line 1, in <module>
spoolman-spoolman-1  |     import asyncio
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/asyncio/__init__.py", line 8, in <module>
spoolman-spoolman-1  |     from .base_events import *
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 18, in <module>
spoolman-spoolman-1  |     import concurrent.futures
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/concurrent/futures/__init__.py", line 8, in <module>
spoolman-spoolman-1  |     from concurrent.futures._base import (FIRST_COMPLETED,
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 7, in <module>
spoolman-spoolman-1  |     import logging
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/logging/__init__.py", line 58, in <module>
spoolman-spoolman-1  |     _startTime = time.time()
spoolman-spoolman-1  |                  ^^^^^^^^^^^
spoolman-spoolman-1  | PermissionError: [Errno 1] Operation not permitted
spoolman-spoolman-1  | Traceback (most recent call last):
spoolman-spoolman-1  |   File "/home/app/.venv/bin/uvicorn", line 5, in <module>
spoolman-spoolman-1  |     from uvicorn.main import main
spoolman-spoolman-1  |   File "/home/app/.venv/lib/python3.11/site-packages/uvicorn/__init__.py", line 1, in <module>
spoolman-spoolman-1  |     from uvicorn.config import Config
spoolman-spoolman-1  |   File "/home/app/.venv/lib/python3.11/site-packages/uvicorn/config.py", line 1, in <module>
spoolman-spoolman-1  |     import asyncio
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/asyncio/__init__.py", line 8, in <module>
spoolman-spoolman-1  |     from .base_events import *
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 18, in <module>
spoolman-spoolman-1  |     import concurrent.futures
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/concurrent/futures/__init__.py", line 8, in <module>
spoolman-spoolman-1  |     from concurrent.futures._base import (FIRST_COMPLETED,
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 7, in <module>
spoolman-spoolman-1  |     import logging
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/logging/__init__.py", line 58, in <module>
spoolman-spoolman-1  |     _startTime = time.time()
spoolman-spoolman-1  |                  ^^^^^^^^^^^
spoolman-spoolman-1  | PermissionError: [Errno 1] Operation not permitted
spoolman-spoolman-1  | Traceback (most recent call last):
spoolman-spoolman-1  |   File "/home/app/.venv/bin/uvicorn", line 5, in <module>
spoolman-spoolman-1  |     from uvicorn.main import main
spoolman-spoolman-1  |   File "/home/app/.venv/lib/python3.11/site-packages/uvicorn/__init__.py", line 1, in <module>
spoolman-spoolman-1  |     from uvicorn.config import Config
spoolman-spoolman-1  |   File "/home/app/.venv/lib/python3.11/site-packages/uvicorn/config.py", line 1, in <module>
spoolman-spoolman-1  |     import asyncio
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/asyncio/__init__.py", line 8, in <module>
spoolman-spoolman-1  |     from .base_events import *
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 18, in <module>
spoolman-spoolman-1  |     import concurrent.futures
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/concurrent/futures/__init__.py", line 8, in <module>
spoolman-spoolman-1  |     from concurrent.futures._base import (FIRST_COMPLETED,
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 7, in <module>
spoolman-spoolman-1  |     import logging
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/logging/__init__.py", line 58, in <module>
spoolman-spoolman-1  |     _startTime = time.time()
spoolman-spoolman-1  |                  ^^^^^^^^^^^
spoolman-spoolman-1  | PermissionError: [Errno 1] Operation not permitted
spoolman-spoolman-1  | Traceback (most recent call last):
spoolman-spoolman-1  |   File "/home/app/.venv/bin/uvicorn", line 5, in <module>
spoolman-spoolman-1  |     from uvicorn.main import main
spoolman-spoolman-1  |   File "/home/app/.venv/lib/python3.11/site-packages/uvicorn/__init__.py", line 1, in <module>
spoolman-spoolman-1  |     from uvicorn.config import Config
spoolman-spoolman-1  |   File "/home/app/.venv/lib/python3.11/site-packages/uvicorn/config.py", line 1, in <module>
spoolman-spoolman-1  |     import asyncio
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/asyncio/__init__.py", line 8, in <module>
spoolman-spoolman-1  |     from .base_events import *
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 18, in <module>
spoolman-spoolman-1  |     import concurrent.futures
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/concurrent/futures/__init__.py", line 8, in <module>
spoolman-spoolman-1  |     from concurrent.futures._base import (FIRST_COMPLETED,
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 7, in <module>
spoolman-spoolman-1  |     import logging
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/logging/__init__.py", line 58, in <module>
spoolman-spoolman-1  |     _startTime = time.time()
spoolman-spoolman-1  |                  ^^^^^^^^^^^
spoolman-spoolman-1  | PermissionError: [Errno 1] Operation not permitted
spoolman-spoolman-1  | Traceback (most recent call last):
spoolman-spoolman-1  |   File "/home/app/.venv/bin/uvicorn", line 5, in <module>
spoolman-spoolman-1  |     from uvicorn.main import main
spoolman-spoolman-1  |   File "/home/app/.venv/lib/python3.11/site-packages/uvicorn/__init__.py", line 1, in <module>
spoolman-spoolman-1  |     from uvicorn.config import Config
spoolman-spoolman-1  |   File "/home/app/.venv/lib/python3.11/site-packages/uvicorn/config.py", line 1, in <module>
spoolman-spoolman-1  |     import asyncio
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/asyncio/__init__.py", line 8, in <module>
spoolman-spoolman-1  |     from .base_events import *
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 18, in <module>
spoolman-spoolman-1  |     import concurrent.futures
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/concurrent/futures/__init__.py", line 8, in <module>
spoolman-spoolman-1  |     from concurrent.futures._base import (FIRST_COMPLETED,
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 7, in <module>
spoolman-spoolman-1  |     import logging
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/logging/__init__.py", line 58, in <module>
spoolman-spoolman-1  |     _startTime = time.time()
spoolman-spoolman-1  |                  ^^^^^^^^^^^
spoolman-spoolman-1  | PermissionError: [Errno 1] Operation not permitted
spoolman-spoolman-1  | Traceback (most recent call last):
spoolman-spoolman-1  |   File "/home/app/.venv/bin/uvicorn", line 5, in <module>
spoolman-spoolman-1  |     from uvicorn.main import main
spoolman-spoolman-1  |   File "/home/app/.venv/lib/python3.11/site-packages/uvicorn/__init__.py", line 1, in <module>
spoolman-spoolman-1  |     from uvicorn.config import Config
spoolman-spoolman-1  |   File "/home/app/.venv/lib/python3.11/site-packages/uvicorn/config.py", line 1, in <module>
spoolman-spoolman-1  |     import asyncio
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/asyncio/__init__.py", line 8, in <module>
spoolman-spoolman-1  |     from .base_events import *
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 18, in <module>
spoolman-spoolman-1  |     import concurrent.futures
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/concurrent/futures/__init__.py", line 8, in <module>
spoolman-spoolman-1  |     from concurrent.futures._base import (FIRST_COMPLETED,
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 7, in <module>
spoolman-spoolman-1  |     import logging
spoolman-spoolman-1  |   File "/usr/local/lib/python3.11/logging/__init__.py", line 58, in <module>
spoolman-spoolman-1  |     _startTime = time.time()
spoolman-spoolman-1  |                  ^^^^^^^^^^^
spoolman-spoolman-1  | PermissionError: [Errno 1] Operation not permitted

**Comment by Donkie** [comment]
This seems to be a known bug on Raspberry Pi 4, is that what you have?

Please follow this blog post and see if it works for you. https://blog.samcater.com/fix-workaround-rpi4-docker-libseccomp2-docker-20/
