### ISSUE TITLE
Update to v0.18.0 not Working

### ISSUE THREAD

**Issue by Gamerou** [Donkie/Spoolman#385]
I have installed Spoolman Standalone and wanted to update it via Mainsail. So I clicked on update. Then ran the install.sh again (no error message or anything). But when I go to the Spoolman page, all I get is: Internal Server Error. Here is the log from journalctl:

May 22 14:35:53 mainsailos bash[585]: FileNotFoundError: [Errno 2] No such file or directory
May 22 14:35:53 mainsailos bash[585]:     cwd = os.getcwd()
May 22 14:35:53 mainsailos bash[585]:   File "/usr/lib/python3.9/posixpath.py", line 379, in abspath
May 22 14:35:53 mainsailos bash[585]:     return abspath(path)
May 22 14:35:53 mainsailos bash[585]:   File "/usr/lib/python3.9/posixpath.py", line 392, in realpath
May 22 14:35:53 mainsailos bash[585]:     full_path = os.path.realpath(joined_path)
May 22 14:35:53 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/staticfiles.py", line 170, in lookup_path
May 22 14:35:53 mainsailos bash[585]:     super().__init__(directory=directory, packages=None, html=True, check_dir=True)
May 22 14:35:53 mainsailos bash[585]:   File "/home/pi/Spoolman/spoolman/client.py", line 20, in lookup_path
May 22 14:35:53 mainsailos bash[585]:     result = context.run(func, *args)
May 22 14:35:53 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
May 22 14:35:53 mainsailos bash[585]:     return await future
May 22 14:35:53 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
May 22 14:35:53 mainsailos bash[585]:     return await get_asynclib().run_sync_in_worker_thread(
May 22 14:35:53 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
May 22 14:35:53 mainsailos bash[585]:     full_path, stat_result = await anyio.to_thread.run_sync(
May 22 14:35:53 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/staticfiles.py", line 121, in get_response
May 22 14:35:53 mainsailos bash[585]:     response = await self.get_response(path, scope)
May 22 14:35:53 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/staticfiles.py", line 103, in __call__
May 22 14:35:53 mainsailos bash[585]:     await self.app(scope, receive, send)
May 22 14:35:53 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/routing.py", line 443, in handle
May 22 14:35:53 mainsailos bash[585]:     await route.handle(scope, receive, send)
May 22 14:35:53 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
May 22 14:35:53 mainsailos bash[585]:     await self.app(scope, receive, send)
May 22 14:35:53 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
May 22 14:35:53 mainsailos bash[585]:     raise e
May 22 14:35:53 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
May 22 14:35:53 mainsailos bash[585]:     await self.app(scope, receive, sender)
May 22 14:35:53 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
May 22 14:35:53 mainsailos bash[585]:     raise exc
May 22 14:35:53 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
May 22 14:35:53 mainsailos bash[585]:     await self.app(scope, receive, self.send_with_gzip)
May 22 14:35:53 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 44, in __call__
May 22 14:35:53 mainsailos bash[585]:     await responder(scope, receive, send)
May 22 14:35:53 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 24, in __call__
May 22 14:35:53 mainsailos bash[585]:     await self.app(scope, receive, _send)
May 22 14:35:53 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
May 22 14:35:53 mainsailos bash[585]:     raise exc
May 22 14:35:53 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
May 22 14:35:53 mainsailos bash[585]:     await self.middleware_stack(scope, receive, send)
May 22 14:35:53 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
May 22 14:35:53 mainsailos bash[585]:     await super().__call__(scope, receive, send)
May 22 14:35:53 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/fastapi/applications.py", line 292, in __call__
May 22 14:35:53 mainsailos bash[585]:     return await self.app(scope, receive, send)
May 22 14:35:53 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
May 22 14:35:53 mainsailos bash[585]:     result = await app(  # type: ignore[func-returns-value]
May 22 14:35:53 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
May 22 14:35:53 mainsailos bash[585]: Traceback (most recent call last):
May 22 14:35:53 mainsailos bash[585]: ERROR:    Exception in ASGI application
May 22 14:35:53 mainsailos bash[585]: INFO:     192.168.178.30:50790 - "GET /favicon.ico HTTP/1.1" 500 Internal Server Error
May 22 14:35:52 mainsailos bash[585]: FileNotFoundError: [Errno 2] No such file or directory
May 22 14:35:52 mainsailos bash[585]:     cwd = os.getcwd()
May 22 14:35:52 mainsailos bash[585]:   File "/usr/lib/python3.9/posixpath.py", line 379, in abspath
May 22 14:35:52 mainsailos bash[585]:     return abspath(path)
May 22 14:35:52 mainsailos bash[585]:   File "/usr/lib/python3.9/posixpath.py", line 392, in realpath
May 22 14:35:52 mainsailos bash[585]:     full_path = os.path.realpath(joined_path)
May 22 14:35:52 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/staticfiles.py", line 170, in lookup_path
May 22 14:35:52 mainsailos bash[585]:     super().__init__(directory=directory, packages=None, html=True, check_dir=True)
May 22 14:35:52 mainsailos bash[585]:   File "/home/pi/Spoolman/spoolman/client.py", line 20, in lookup_path
May 22 14:35:52 mainsailos bash[585]:     result = context.run(func, *args)
May 22 14:35:52 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
May 22 14:35:52 mainsailos bash[585]:     return await future
May 22 14:35:52 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
May 22 14:35:52 mainsailos bash[585]:     return await get_asynclib().run_sync_in_worker_thread(
May 22 14:35:52 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
May 22 14:35:52 mainsailos bash[585]:     full_path, stat_result = await anyio.to_thread.run_sync(
May 22 14:35:52 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/staticfiles.py", line 121, in get_response
May 22 14:35:52 mainsailos bash[585]:     response = await self.get_response(path, scope)
May 22 14:35:52 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/staticfiles.py", line 103, in __call__
May 22 14:35:52 mainsailos bash[585]:     await self.app(scope, receive, send)
May 22 14:35:52 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/routing.py", line 443, in handle
May 22 14:35:52 mainsailos bash[585]:     await route.handle(scope, receive, send)
May 22 14:35:52 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
May 22 14:35:52 mainsailos bash[585]:     await self.app(scope, receive, send)
May 22 14:35:52 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
May 22 14:35:52 mainsailos bash[585]:     raise e
May 22 14:35:52 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
May 22 14:35:52 mainsailos bash[585]:     await self.app(scope, receive, sender)
May 22 14:35:52 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
May 22 14:35:52 mainsailos bash[585]:     raise exc
May 22 14:35:52 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
May 22 14:35:52 mainsailos bash[585]:     await self.app(scope, receive, self.send_with_gzip)
May 22 14:35:52 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 44, in __call__
May 22 14:35:52 mainsailos bash[585]:     await responder(scope, receive, send)
May 22 14:35:52 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 24, in __call__
May 22 14:35:52 mainsailos bash[585]:     await self.app(scope, receive, _send)
May 22 14:35:52 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
May 22 14:35:52 mainsailos bash[585]:     raise exc
May 22 14:35:52 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
May 22 14:35:52 mainsailos bash[585]:     await self.middleware_stack(scope, receive, send)
May 22 14:35:52 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
May 22 14:35:52 mainsailos bash[585]:     await super().__call__(scope, receive, send)
May 22 14:35:52 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/fastapi/applications.py", line 292, in __call__
May 22 14:35:52 mainsailos bash[585]:     return await self.app(scope, receive, send)
May 22 14:35:52 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
May 22 14:35:52 mainsailos bash[585]:     result = await app(  # type: ignore[func-returns-value]
May 22 14:35:52 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
May 22 14:35:52 mainsailos bash[585]: Traceback (most recent call last):
May 22 14:35:52 mainsailos bash[585]: ERROR:    Exception in ASGI application
May 22 14:35:52 mainsailos bash[585]: INFO:     192.168.178.30:50789 - "GET / HTTP/1.1" 500 Internal Server Error
May 22 14:35:51 mainsailos bash[585]: FileNotFoundError: [Errno 2] No such file or directory
May 22 14:35:51 mainsailos bash[585]:     cwd = os.getcwd()
May 22 14:35:51 mainsailos bash[585]:   File "/usr/lib/python3.9/posixpath.py", line 379, in abspath
May 22 14:35:51 mainsailos bash[585]:     return abspath(path)
May 22 14:35:51 mainsailos bash[585]:   File "/usr/lib/python3.9/posixpath.py", line 392, in realpath
May 22 14:35:51 mainsailos bash[585]:     full_path = os.path.realpath(joined_path)
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/staticfiles.py", line 170, in lookup_path
May 22 14:35:51 mainsailos bash[585]:     super().__init__(directory=directory, packages=None, html=True, check_dir=True)
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/spoolman/client.py", line 20, in lookup_path
May 22 14:35:51 mainsailos bash[585]:     result = context.run(func, *args)
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
May 22 14:35:51 mainsailos bash[585]:     return await future
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
May 22 14:35:51 mainsailos bash[585]:     return await get_asynclib().run_sync_in_worker_thread(
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
May 22 14:35:51 mainsailos bash[585]:     full_path, stat_result = await anyio.to_thread.run_sync(
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/staticfiles.py", line 121, in get_response
May 22 14:35:51 mainsailos bash[585]:     response = await self.get_response(path, scope)
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/staticfiles.py", line 103, in __call__
May 22 14:35:51 mainsailos bash[585]:     await self.app(scope, receive, send)
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/routing.py", line 443, in handle
May 22 14:35:51 mainsailos bash[585]:     await route.handle(scope, receive, send)
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
May 22 14:35:51 mainsailos bash[585]:     await self.app(scope, receive, send)
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
May 22 14:35:51 mainsailos bash[585]:     raise e
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
May 22 14:35:51 mainsailos bash[585]:     await self.app(scope, receive, sender)
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
May 22 14:35:51 mainsailos bash[585]:     raise exc
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
May 22 14:35:51 mainsailos bash[585]:     await self.app(scope, receive, self.send_with_gzip)
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 44, in __call__
May 22 14:35:51 mainsailos bash[585]:     await responder(scope, receive, send)
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 24, in __call__
May 22 14:35:51 mainsailos bash[585]:     await self.app(scope, receive, _send)
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
May 22 14:35:51 mainsailos bash[585]:     raise exc
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
May 22 14:35:51 mainsailos bash[585]:     await self.middleware_stack(scope, receive, send)
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
May 22 14:35:51 mainsailos bash[585]:     await super().__call__(scope, receive, send)
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/fastapi/applications.py", line 292, in __call__
May 22 14:35:51 mainsailos bash[585]:     return await self.app(scope, receive, send)
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
May 22 14:35:51 mainsailos bash[585]:     result = await app(  # type: ignore[func-returns-value]
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
May 22 14:35:51 mainsailos bash[585]: Traceback (most recent call last):
May 22 14:35:51 mainsailos bash[585]: ERROR:    Exception in ASGI application
May 22 14:35:51 mainsailos bash[585]: INFO:     192.168.178.30:50787 - "GET /favicon.ico HTTP/1.1" 500 Internal Server Error
May 22 14:35:51 mainsailos bash[585]: FileNotFoundError: [Errno 2] No such file or directory
May 22 14:35:51 mainsailos bash[585]:     cwd = os.getcwd()
May 22 14:35:51 mainsailos bash[585]:   File "/usr/lib/python3.9/posixpath.py", line 379, in abspath
May 22 14:35:51 mainsailos bash[585]:     return abspath(path)
May 22 14:35:51 mainsailos bash[585]:   File "/usr/lib/python3.9/posixpath.py", line 392, in realpath
May 22 14:35:51 mainsailos bash[585]:     full_path = os.path.realpath(joined_path)
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/staticfiles.py", line 170, in lookup_path
May 22 14:35:51 mainsailos bash[585]:     super().__init__(directory=directory, packages=None, html=True, check_dir=True)
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/spoolman/client.py", line 20, in lookup_path
May 22 14:35:51 mainsailos bash[585]:     result = context.run(func, *args)
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
May 22 14:35:51 mainsailos bash[585]:     return await future
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
May 22 14:35:51 mainsailos bash[585]:     return await get_asynclib().run_sync_in_worker_thread(
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
May 22 14:35:51 mainsailos bash[585]:     full_path, stat_result = await anyio.to_thread.run_sync(
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/staticfiles.py", line 121, in get_response
May 22 14:35:51 mainsailos bash[585]:     response = await self.get_response(path, scope)
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/staticfiles.py", line 103, in __call__
May 22 14:35:51 mainsailos bash[585]:     await self.app(scope, receive, send)
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/routing.py", line 443, in handle
May 22 14:35:51 mainsailos bash[585]:     await route.handle(scope, receive, send)
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
May 22 14:35:51 mainsailos bash[585]:     await self.app(scope, receive, send)
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
May 22 14:35:51 mainsailos bash[585]:     raise e
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
May 22 14:35:51 mainsailos bash[585]:     await self.app(scope, receive, sender)
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
May 22 14:35:51 mainsailos bash[585]:     raise exc
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
May 22 14:35:51 mainsailos bash[585]:     await self.app(scope, receive, self.send_with_gzip)
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 44, in __call__
May 22 14:35:51 mainsailos bash[585]:     await responder(scope, receive, send)
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 24, in __call__
May 22 14:35:51 mainsailos bash[585]:     await self.app(scope, receive, _send)
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
May 22 14:35:51 mainsailos bash[585]:     raise exc
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
May 22 14:35:51 mainsailos bash[585]:     await self.middleware_stack(scope, receive, send)
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
May 22 14:35:51 mainsailos bash[585]:     await super().__call__(scope, receive, send)
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/fastapi/applications.py", line 292, in __call__
May 22 14:35:51 mainsailos bash[585]:     return await self.app(scope, receive, send)
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
May 22 14:35:51 mainsailos bash[585]:     result = await app(  # type: ignore[func-returns-value]
May 22 14:35:51 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
May 22 14:35:51 mainsailos bash[585]: Traceback (most recent call last):
May 22 14:35:51 mainsailos bash[585]: ERROR:    Exception in ASGI application
May 22 14:35:51 mainsailos bash[585]: INFO:     192.168.178.30:50786 - "GET / HTTP/1.1" 500 Internal Server Error
May 22 14:35:22 mainsailos bash[585]: INFO:     127.0.0.1:33984 - "GET /spool/5 HTTP/1.1" 200 OK
May 22 14:35:22 mainsailos bash[585]: INFO:     127.0.0.1:33960 - "GET /vendor HTTP/1.1" 200 OK
May 22 14:35:22 mainsailos bash[585]: FileNotFoundError: [Errno 2] No such file or directory: 'pyproject.toml'
May 22 14:35:22 mainsailos bash[585]:     return self._accessor.open(self, flags, mode)
May 22 14:35:22 mainsailos bash[585]:   File "/usr/lib/python3.9/pathlib.py", line 1109, in _opener
May 22 14:35:22 mainsailos bash[585]:     return io.open(self, mode, buffering, encoding, errors, newline,
May 22 14:35:22 mainsailos bash[585]:   File "/usr/lib/python3.9/pathlib.py", line 1241, in open
May 22 14:35:22 mainsailos bash[585]:     with Path("pyproject.toml").open(encoding="utf-8") as f:
May 22 14:35:22 mainsailos bash[585]:   File "/home/pi/Spoolman/spoolman/env.py", line 274, in get_version
May 22 14:35:22 mainsailos bash[585]:     version=env.get_version(),
May 22 14:35:22 mainsailos bash[585]:   File "/home/pi/Spoolman/spoolman/api/v1/router.py", line 51, in info
May 22 14:35:22 mainsailos bash[585]:     return await dependant.call(**values)
May 22 14:35:22 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
May 22 14:35:22 mainsailos bash[585]:     raw_response = await run_endpoint_function(
May 22 14:35:22 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 273, in app
May 22 14:35:22 mainsailos bash[585]:     response = await func(request)
May 22 14:35:22 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
May 22 14:35:22 mainsailos bash[585]:     await self.app(scope, receive, send)
May 22 14:35:22 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
May 22 14:35:22 mainsailos bash[585]:     await route.handle(scope, receive, send)
May 22 14:35:22 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
May 22 14:35:22 mainsailos bash[585]:     await self.app(scope, receive, send)
May 22 14:35:22 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
May 22 14:35:22 mainsailos bash[585]:     raise e
May 22 14:35:22 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
May 22 14:35:22 mainsailos bash[585]:     await self.app(scope, receive, sender)
May 22 14:35:22 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
May 22 14:35:22 mainsailos bash[585]:     raise exc
May 22 14:35:22 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
May 22 14:35:22 mainsailos bash[585]:     await self.app(scope, receive, _send)
May 22 14:35:22 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
May 22 14:35:22 mainsailos bash[585]:     raise exc
May 22 14:35:22 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
May 22 14:35:22 mainsailos bash[585]:     await self.middleware_stack(scope, receive, send)
May 22 14:35:22 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
May 22 14:35:22 mainsailos bash[585]:     await super().__call__(scope, receive, send)
May 22 14:35:22 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/fastapi/applications.py", line 292, in __call__
May 22 14:35:22 mainsailos bash[585]:     await self.app(scope, receive, send)
May 22 14:35:22 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/routing.py", line 443, in handle
May 22 14:35:22 mainsailos bash[585]:     await route.handle(scope, receive, send)
May 22 14:35:22 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
May 22 14:35:22 mainsailos bash[585]:     await self.app(scope, receive, send)
May 22 14:35:22 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
May 22 14:35:22 mainsailos bash[585]:     raise e
May 22 14:35:22 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
May 22 14:35:22 mainsailos bash[585]:     await self.app(scope, receive, sender)
May 22 14:35:22 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
May 22 14:35:22 mainsailos bash[585]:     raise exc
May 22 14:35:22 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
May 22 14:35:22 mainsailos bash[585]:     await self.app(scope, receive, self.send_with_gzip)
May 22 14:35:22 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 44, in __call__
May 22 14:35:22 mainsailos bash[585]:     await responder(scope, receive, send)
May 22 14:35:22 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 24, in __call__
May 22 14:35:22 mainsailos bash[585]:     await self.app(scope, receive, _send)
May 22 14:35:22 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
May 22 14:35:22 mainsailos bash[585]:     raise exc
May 22 14:35:22 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
May 22 14:35:22 mainsailos bash[585]:     await self.middleware_stack(scope, receive, send)
May 22 14:35:22 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
May 22 14:35:22 mainsailos bash[585]:     await super().__call__(scope, receive, send)
May 22 14:35:22 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/fastapi/applications.py", line 292, in __call__
May 22 14:35:22 mainsailos bash[585]:     return await self.app(scope, receive, send)
May 22 14:35:22 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
May 22 14:35:22 mainsailos bash[585]:     result = await app(  # type: ignore[func-returns-value]
May 22 14:35:22 mainsailos bash[585]:   File "/home/pi/Spoolman/.venv/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
May 22 14:35:22 mainsailos bash[585]: Traceback (most recent call last):
May 22 14:35:22 mainsailos bash[585]: ERROR:    Exception in ASGI application
May 22 14:35:22 mainsailos bash[585]: INFO:     127.0.0.1:33970 - "GET /info HTTP/1.1" 500 Internal Server Error
May 22 14:35:22 mainsailos bash[585]: INFO:     127.0.0.1:33944 - "GET /health HTTP/1.1" 200 OK

**Comment by Gamerou** [comment]
I'll try the normal update now, not via Mainsail
