### ISSUE TITLE
Application startup failed

### ISSUE THREAD

**Issue by Lavve** [Donkie/Spoolman#407]
**Describe the bug**
Since a few days ago the Spoolman won't start. Checking the logs I, repeatedly, get the error message below. I did no changes to either Spoolman and it's data.
I've added the `export PATH=/home/lavve/.local/bin:$PATH` to the .bashrc file but still gets the same message in the log file after reboot.
Not sure how to go on from this.

**To Reproduce**
I have no idea

**Expected behavior**
A functional integration of Spoolman

**Spoolman Host (please complete the following information):**
 - Installation type: Via Octoprint
 - Installed version: Since I can't reach the webside I'm not sure, but I guess it's the latest version 0.18.1
 - Database type: SQLite I guess

**The error message**
```
Jun 17 18:59:00 octopi bash[31465]: INFO:     Started server process [31465]
Jun 17 18:59:00 octopi bash[31465]: INFO:     Waiting for application startup.
Jun 17 18:59:00 octopi bash[31465]: spoolman.main              INFO     Starting Spoolman v0.18.1 (commit: 306dbe4) (built: None)
Jun 17 18:59:00 octopi bash[31465]: spoolman.main              INFO     Using data directory: /home/lavve/spoolman_data
Jun 17 18:59:00 octopi bash[31465]: spoolman.main              INFO     Using logs directory: /home/lavve/spoolman_data
Jun 17 18:59:00 octopi bash[31465]: spoolman.main              INFO     Using backups directory: /home/lavve/spoolman_data/backups
Jun 17 18:59:00 octopi bash[31465]: spoolman.main              INFO     Setting up database...
Jun 17 18:59:00 octopi bash[31465]: ERROR:    Traceback (most recent call last):
Jun 17 18:59:00 octopi bash[31465]:   File "/home/lavve/Spoolman/.venv/lib/python3.9/site-packages/starlette/routing.py", line 677, in lifespan
Jun 17 18:59:00 octopi bash[31465]:     async with self.lifespan_context(app) as maybe_state:
Jun 17 18:59:00 octopi bash[31465]:   File "/home/lavve/Spoolman/.venv/lib/python3.9/site-packages/starlette/routing.py", line 566, in __aenter__
Jun 17 18:59:00 octopi bash[31465]:     await self._router.startup()
Jun 17 18:59:00 octopi bash[31465]:   File "/home/lavve/Spoolman/.venv/lib/python3.9/site-packages/starlette/routing.py", line 654, in startup
Jun 17 18:59:00 octopi bash[31465]:     await handler()
Jun 17 18:59:00 octopi bash[31465]:   File "/home/lavve/Spoolman/spoolman/main.py", line 134, in startup
Jun 17 18:59:00 octopi bash[31465]:     database.setup_db(database.get_connection_url())
Jun 17 18:59:00 octopi bash[31465]:   File "/home/lavve/Spoolman/spoolman/database/database.py", line 39, in get_connection_url
Jun 17 18:59:00 octopi bash[31465]:     raise ValueError("Cannot specify a database name when using SQLite.")
Jun 17 18:59:00 octopi bash[31465]: ValueError: Cannot specify a database name when using SQLite.
Jun 17 18:59:00 octopi bash[31465]: ERROR:    Application startup failed. Exiting.
Jun 17 18:59:01 octopi systemd[1]: Spoolman.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Jun 17 18:59:01 octopi systemd[1]: Spoolman.service: Failed with result 'exit-code'.
Jun 17 18:59:01 octopi systemd[1]: Spoolman.service: Consumed 2.864s CPU time.
Jun 17 18:59:01 octopi systemd[1]: Spoolman.service: Scheduled restart job, restart counter is at 48.
Jun 17 18:59:01 octopi systemd[1]: Stopped Spoolman.
Jun 17 18:59:01 octopi systemd[1]: Spoolman.service: Consumed 2.864s CPU time.
Jun 17 18:59:01 octopi systemd[1]: Started Spoolman.
Jun 17 18:59:01 octopi bash[31467]: WARNING: /home/lavve/.local/bin is not in PATH, this will make it difficult to run PDM commands. Temporarily adding /home/lavve/.local/bin to PATH...
Jun 17 18:59:01 octopi bash[31467]: To make this permanent, add the following line to your .bashrc or .zshrc file:
Jun 17 18:59:01 octopi bash[31467]: export PATH=/home/lavve/.local/bin:$PATH
Jun 17 18:59:01 octopi bash[31467]: Activating .venv...
Jun 17 18:59:01 octopi bash[31467]: Starting Spoolman...
```

**Comment by Donkie** [comment]
Sorry for the late response.

For some reason the environment variable `SPOOLMAN_DB_NAME` is set to something, which isn't compatible while using the SQLite database type.

Make sure the SPOOLMAN_DB_NAME line is commented out in your Spoolman's .env file
