### ISSUE TITLE
No spool filament usage

### ISSUE THREAD

**Issue by Hesi-Re** [Donkie/Spoolman#47]
I'm running Spoolman with Docker. I can SET_ACTIVE_SPOOL ID=1 and confirm the spool is activated at http://mylocalprinterir:7125/server/spoolman/spool_id:

{"result": {"spool_id": 1}}

After printer job complete, Spoolman doesn't register the filament usage as supposed.

When looking in moonraker.log I can see this:

2023-07-15 19:12:18,321 [server.py:_process_event()] - 
Error processing callback in event server:status_update
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/components/http_client.py", line 115, in request
    resp = await asyncio.wait_for(fut, timeout)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
tornado.simple_httpclient.HTTPTimeoutError: Timeout while connecting

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/components/spoolman.py", line 112, in _handle_status_update
    await self.track_filament_usage()
  File "/home/pi/moonraker/moonraker/components/spoolman.py", line 152, in track_filament_usage
    response.raise_for_status()
  File "/home/pi/moonraker/moonraker/components/http_client.py", line 363, in raise_for_status
    raise ServerError(msg, code) from self._error
moonraker.utils.ServerError: Timeout while connecting

How can I solve this problem?

**Comment by Donkie** [comment]
Well Moonraker isn't able to communicate with Spoolman. It's hard to say why that would be the case.

If you input the following in the SSH of the host you run Moonraker on:

`curl http://spoolmanip:port/api/v1/info`

Where the beginning ip and port is what you put in the moonraker config, what happens then?

It should also fail.

**Comment by Hesi-Re** [comment]
Thanks you very much. It was my fault. I forgot to change the IP in moonraker.conf.
