### ISSUE TITLE
Upgrade from 0.18.1 to 0.19.3 fails, database migration crashes

### ISSUE THREAD

**Issue by einarjh** [Donkie/Spoolman#474]
**Describe the bug**
I upgraded my Spoolman instance from 0.18.1 to 0.19.3 today, but the application did not come back up. The logs show the following (repeated endlessly):

```
spoolman_1  | usermod: no changes
spoolman_1  | User UID: 1000
spoolman_1  | User GID: 1000
spoolman_1  | Starting uvicorn...
spoolman_1  | INFO:     Started server process [1]
spoolman_1  | INFO:     Waiting for application startup.
spoolman_1  | spoolman.main              INFO     Starting Spoolman v0.19.3 (commit: 5c5bd46) (built: 2024-08-10 09:59:51+00:00)
spoolman_1  | spoolman.main              INFO     Using data directory: /home/app/.local/share/spoolman
spoolman_1  | spoolman.main              INFO     Using logs directory: /home/app/.local/share/spoolman
spoolman_1  | spoolman.main              INFO     Using backups directory: /home/app/.local/share/spoolman/backups
spoolman_1  | spoolman.main              INFO     Setting up database...
spoolman_1  | spoolman.database.database INFO     No database type specified, using a default SQLite database located at "/home/app/.local/share/spoolman/spoolman.db"
spoolman_1  | spoolman.main              INFO     Performing migrations...
spoolman_1  | Traceback (most recent call last):
spoolman_1  |   File "/home/app/spoolman/.venv/bin/alembic", line 8, in <module>
spoolman_1  |     sys.exit(main())
spoolman_1  |              ^^^^^^
spoolman_1  |   File "/home/app/spoolman/.venv/lib/python3.11/site-packages/alembic/config.py", line 636, in main
spoolman_1  |     CommandLine(prog=prog).main(argv=argv)
spoolman_1  |   File "/home/app/spoolman/.venv/lib/python3.11/site-packages/alembic/config.py", line 626, in main
spoolman_1  |     self.run_cmd(cfg, options)
spoolman_1  |   File "/home/app/spoolman/.venv/lib/python3.11/site-packages/alembic/config.py", line 603, in run_cmd
spoolman_1  |     fn(
spoolman_1  |   File "/home/app/spoolman/.venv/lib/python3.11/site-packages/alembic/command.py", line 406, in upgrade
spoolman_1  |     script.run_env()
spoolman_1  |   File "/home/app/spoolman/.venv/lib/python3.11/site-packages/alembic/script/base.py", line 582, in run_env
spoolman_1  |     util.load_python_file(self.dir, "env.py")
spoolman_1  |   File "/home/app/spoolman/.venv/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
spoolman_1  |     module = load_module_py(module_id, path)
spoolman_1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spoolman_1  |   File "/home/app/spoolman/.venv/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
spoolman_1  |     spec.loader.exec_module(module)  # type: ignore
spoolman_1  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spoolman_1  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
spoolman_1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
spoolman_1  |   File "/home/app/spoolman/migrations/env.py", line 69, in <module>
spoolman_1  |     asyncio.run(run_async_migrations())
spoolman_1  |   File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
spoolman_1  |     return runner.run(main)
spoolman_1  |            ^^^^^^^^^^^^^^^^
spoolman_1  |   File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
spoolman_1  |     return self._loop.run_until_complete(task)
spoolman_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spoolman_1  |   File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
spoolman_1  |     return future.result()
spoolman_1  |            ^^^^^^^^^^^^^^^
spoolman_1  |   File "/home/app/spoolman/migrations/env.py", line 60, in run_async_migrations
spoolman_1  |     async with db.engine.connect() as connection:
spoolman_1  |   File "/home/app/spoolman/.venv/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/base.py", line 121, in __aenter__
spoolman_1  |     return await self.start(is_ctxmanager=True)
spoolman_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spoolman_1  |   File "/home/app/spoolman/.venv/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/engine.py", line 273, in start
spoolman_1  |     await greenlet_spawn(self.sync_engine.connect)
spoolman_1  |   File "/home/app/spoolman/.venv/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 201, in greenlet_spawn
spoolman_1  |     result = context.throw(*sys.exc_info())
spoolman_1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spoolman_1  |   File "/home/app/spoolman/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3276, in connect
spoolman_1  |     return self._connection_cls(self)
spoolman_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
spoolman_1  |   File "/home/app/spoolman/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
spoolman_1  |     self._dbapi_connection = engine.raw_connection()
spoolman_1  |                              ^^^^^^^^^^^^^^^^^^^^^^^
spoolman_1  |   File "/home/app/spoolman/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3300, in raw_connection
spoolman_1  |     return self.pool.connect()
spoolman_1  |            ^^^^^^^^^^^^^^^^^^^
spoolman_1  |   File "/home/app/spoolman/.venv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 449, in connect
spoolman_1  |     return _ConnectionFairy._checkout(self)
spoolman_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spoolman_1  |   File "/home/app/spoolman/.venv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
spoolman_1  |     fairy = _ConnectionRecord.checkout(pool)
spoolman_1  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spoolman_1  |   File "/home/app/spoolman/.venv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
spoolman_1  |     rec = pool._do_get()
spoolman_1  |           ^^^^^^^^^^^^^^
spoolman_1  |   File "/home/app/spoolman/.venv/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 308, in _do_get
spoolman_1  |     return self._create_connection()
spoolman_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
spoolman_1  |   File "/home/app/spoolman/.venv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
spoolman_1  |     return _ConnectionRecord(self)
spoolman_1  |            ^^^^^^^^^^^^^^^^^^^^^^^
spoolman_1  |   File "/home/app/spoolman/.venv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
spoolman_1  |     self.__connect()
spoolman_1  |   File "/home/app/spoolman/.venv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
spoolman_1  |     with util.safe_reraise():
spoolman_1  |   File "/home/app/spoolman/.venv/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
spoolman_1  |     raise exc_value.with_traceback(exc_tb)
spoolman_1  |   File "/home/app/spoolman/.venv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
spoolman_1  |     self.dbapi_connection = connection = pool._invoke_creator(self)
spoolman_1  |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
spoolman_1  |   File "/home/app/spoolman/.venv/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 643, in connect
spoolman_1  |     return dialect.connect(*cargs, **cparams)
spoolman_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spoolman_1  |   File "/home/app/spoolman/.venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 620, in connect
spoolman_1  |     return self.loaded_dbapi.connect(*cargs, **cparams)
spoolman_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spoolman_1  |   File "/home/app/spoolman/.venv/lib/python3.11/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 352, in connect
spoolman_1  |     await_only(connection),
spoolman_1  |     ^^^^^^^^^^^^^^^^^^^^^^
spoolman_1  |   File "/home/app/spoolman/.venv/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
spoolman_1  |     return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
spoolman_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spoolman_1  |   File "/home/app/spoolman/.venv/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
spoolman_1  |     value = await result
spoolman_1  |             ^^^^^^^^^^^^
spoolman_1  |   File "/home/app/spoolman/.venv/lib/python3.11/site-packages/aiosqlite/core.py", line 149, in __await__
spoolman_1  |     self.start()
spoolman_1  |   File "/usr/lib/python3.11/threading.py", line 957, in start
spoolman_1  |     _start_new_thread(self._bootstrap, ())
spoolman_1  | RuntimeError: can't start new thread
spoolman_1  | ERROR:    Traceback (most recent call last):
spoolman_1  |   File "/home/app/spoolman/.venv/lib/python3.11/site-packages/starlette/routing.py", line 732, in lifespan
spoolman_1  |     async with self.lifespan_context(app) as maybe_state:
spoolman_1  |   File "/home/app/spoolman/.venv/lib/python3.11/site-packages/starlette/routing.py", line 608, in __aenter__
spoolman_1  |     await self._router.startup()
spoolman_1  |   File "/home/app/spoolman/.venv/lib/python3.11/site-packages/starlette/routing.py", line 709, in startup
spoolman_1  |     await handler()
spoolman_1  |   File "/home/app/spoolman/spoolman/main.py", line 141, in startup
spoolman_1  |     subprocess.run(["alembic", "upgrade", "head"], check=True, cwd=project_root)  # noqa: S603, S607, ASYNC101
spoolman_1  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spoolman_1  |   File "/usr/lib/python3.11/subprocess.py", line 571, in run
spoolman_1  |     raise CalledProcessError(retcode, process.args,
spoolman_1  | subprocess.CalledProcessError: Command '['alembic', 'upgrade', 'head']' returned non-zero exit status 1.
spoolman_1  | 
spoolman_1  | ERROR:    Application startup failed. Exiting.

```
My database has 82 spools registered, so I would prefer if I didn't have to start from scratch. The database appears untouched after the crash, so nothing is ever written to it.

**To Reproduce**

docker-compose pull
docker-compose up -d

**Expected behavior**
The application survives an upgrade.

**Screenshots**
Not applicable

**Spoolman Host (please complete the following information):**
 - Installation type: Docker
 - Installed version: 0.19.3
 - OS and Distro: Debian 10
 - Database type: SQLite

**Desktop (please complete the following information):**
Not applicable

**Additional context**
I can provide a copy of the database if required.

**Comment by AlexTheGreat1971** [comment]
I have a similar problem (it was described at #404), but the data base itself is alive, just Vendors data has fallen off (Error 500).

**Steps to reproduce the behavior:**

- Open Spoolman page (all stats open and are correct)
- Click on Vendors list
- Loads for a while and then throws 500 error
- 
**Expected behavior**
A list of Vendors.

Installation type: Standalone
Installed version: 1.19.3
OS and Distro: Debian 24.04 / OpenNept4une
Database type: SQLite

This happened after the update to 0.19.2-0.19.3
The number of manufacturers is indicated on the main page, but when I log in, I get an error of 500. Neither sorting nor resetting filters solves the problem. I tried to replace the database file with backuped ones. Then manufacturers start to be displayed, but then spools or filaments data being fallen off.

**Comment by KC703** [comment]
During a recent update, I realized my db was moved to .local/shared/spoolman.  Check if a spoolman.db exists in that location.

**Comment by AlexTheGreat1971** [comment]
Spoolman 0.20 does not fix my problem

**Comment by einarjh** [comment]
The issue in this bug report still exists in version 0.20.0. I have also tried upgrading from 0.18.1 to 0.19.0, which was the release immediately after 0.18.1, so the bug was introduced in 0.19.0

@AlexTheGreat1971 I'm pretty sure that your issue is not related to this bug report. This issue is with database migration during an upgrade, and the crash prevents the application from starting at all. 

@KC703 It sounds like you were running from a manual install, I am using the container, which does not even have the ability to move anything to my .local folder.

**Comment by psyipm** [comment]
Not sure if I had the same issue, but in my case there was an error about duplicate column `spool.price`. Removing it from the table solved the problem with the migration.

```sql
ALTER TABLE spool DROP COLUMN price;
```

**Comment by einarjh** [comment]
I finally got round to taking another stab at this error, and it turns out to be something to do with docker on my machine. I copied my database file to a different machine running Debian 12, and that ran the upgrade just fine.

I'm closing this bug, but it seems the app is not compatible with the built-in docker on Debian 10 (Docker version 18.09.1)
