### ISSUE TITLE
Exception in ASGI application

### ISSUE THREAD

**Issue by brocasm** [Donkie/Spoolman#55]
After a fresh install with this documentation: https://github.com/Donkie/Spoolman/issues/43

I have start the service with:
`/home/pi/spoolman-env/bin/uvicorn spoolman.main:app --host 0.0.0.0 --port 8000`

The start correctly, but when a try to add a vendors, a Filaments or Spools i have this error 500:

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/starlette/routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/pi/spoolman/spoolman/api/v1/vendor.py", line 93, in create
    return Vendor.from_db(db_item)
  File "/home/pi/spoolman/spoolman/api/v1/models.py", line 27, in from_db
    registered=item.registered,
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 563, in __get__
    return self.impl.get(state, dict_)  # type: ignore[no-any-return]
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 1083, in get
    value = self._fire_loader_callables(state, key, passive)
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 1113, in _fire_loader_callables
    return state._load_expired(state, passive)
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/sqlalchemy/orm/state.py", line 798, in _load_expired
    self.manager.expired_attribute_loader(self, toload, passive)
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 1617, in load_scalar_attributes
    result = load_on_ident(
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 481, in load_on_ident
    return load_on_pk_identity(
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 666, in load_on_pk_identity
    session.execute(
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2246, in execute
    return self._execute_internal(
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2141, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2342, in _handle_dbapi_exception
    raise exc_info[1].with_traceback(exc_info[2])
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 113, in execute
    self._adapt_connection._handle_exception(error)
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 263, in _handle_exception
    raise error
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 90, in execute
    _cursor = self.await_(self._connection.cursor())
  File "/home/pi/spoolman-env/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 116, in await_only
    raise exc.MissingGreenlet(
sqlalchemy.exc.MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)

```

**Comment by Donkie** [comment]
This is one reason why I've not yet created an official way to run Spoolman outside of Docker. The dependencies needed for different systems are not trivial to resolve.

Please run it using Docker instead. It does not add any noticable overhead consumption.

**Comment by LukysGaming** [comment]
same issue, running on vps
