### ISSUE TITLE
Finish "wood" in external DB breaks import

### ISSUE THREAD

**Issue by tkaufmann** [Donkie/Spoolman#579]
7 days ago, a new filament has been added to the DB. It's id is "numakers_pla+_woodnatural_1000_175_n". It's finish is "wood". This is currently breaking database import for me on a fresh, docker-based instance of Spoolman:

`2024-12-29 02:06:31:INFO:Scheduling external DB sync.
2024-12-29 02:06:31:INFO:Startup complete.
2024-12-29 02:06:31:INFO:Syncing external DB.
2024-12-29 02:06:31:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/filaments.json "HTTP/1.1 200 OK"
2024-12-29 02:06:31:ERROR:Unhandled exception in `scheduler.asyncio.job.Job(<JobType.CYCLIC: 1>, [datetime.timedelta(0)], <function _sync at 0x7f16a11e9760>, (), {}, 1, True, datetime.datetime(2024, 12, 29, 2, 6, 31, 422565), None, False, None, None)`!
Traceback (most recent call last):
  File "/home/app/spoolman/.venv/lib/python3.11/site-packages/scheduler/asyncio/job.py", line 64, in _exec
    await coroutine
  File "/home/app/spoolman/spoolman/externaldb.py", line 173, in _sync
    filaments = _parse_filaments_from_bytes(await _download_file(url + "filaments.json"))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/spoolman/spoolman/externaldb.py", line 145, in _parse_filaments_from_bytes
    return ExternalFilamentsFile.parse_raw(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/spoolman/.venv/lib/python3.11/site-packages/pydantic/main.py", line 1277, in parse_raw
    return cls.model_validate(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/spoolman/.venv/lib/python3.11/site-packages/pydantic/main.py", line 627, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for ExternalFilamentsFile
2996.finish
  Input should be 'matte' or 'glossy' [type=enum, input_value='wood', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/enum`

externaldb.py currently defines: 

`class Finish(Enum):
    MATTE = "matte"
    GLOSSY = "glossy"`

Meanwhile, SpoolmanDB defines those finishes only as examples, which to me sounds as if adding new finishes is allowed from a database design point of view.

**Comment by Donkie** [comment]
Thanks for noticing, I removed the wood finish in spoolmandb. I forgot support needs to be added here first hehe

**Comment by Donkie** [comment]
See if it works better now

**Comment by tkaufmann** [comment]
👍🏻
